version: '3'
services:
  web:
    build: .
    ports:
      - "5002:5002"  
    volumes:
      - ./data:/app/data
    env_file:
      - .env  
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped  